const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const defaults=['Planificar el día','Trabajar en el proyecto','Entrenar','Leer algo','Tiempo libre','Ser la mejor versión de ti'];
let tasks=JSON.parse(localStorage.getItem('nexusTasks2')||'null')||defaults.map((text,i)=>({id:Date.now()+i,text,done:i===0}));
const save=()=>localStorage.setItem('nexusTasks2',JSON.stringify(tasks));
function render(){const html=tasks.map(t=>`<label class="task-row ${t.done?'done':''}"><input type="checkbox" data-id="${t.id}" ${t.done?'checked':''}><span>${t.text.replace(/[<>]/g,'')}</span></label>`).join('');$('#taskList').innerHTML=html;$('#taskListFull').innerHTML=html;$$('.task-row input').forEach(x=>x.onchange=()=>{const t=tasks.find(t=>t.id==x.dataset.id);if(t)t.done=x.checked;save();render()})}
$('#addTaskBtn').onclick=()=>{$('#taskForm').classList.toggle('hidden');$('#taskInput').focus()};$('#taskForm').onsubmit=e=>{e.preventDefault();const v=$('#taskInput').value.trim();if(v){tasks.push({id:Date.now(),text:v,done:false});save();render();$('#taskInput').value='';$('#taskForm').classList.add('hidden')}};
function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));lucide.createIcons()}$$('.nav').forEach(n=>n.onclick=()=>navigate(n.dataset.view));
function clock(){const d=new Date(),time=d.toLocaleTimeString('es-UY',{hour:'2-digit',minute:'2-digit'});$('#clock').textContent=time;$('#bigClock').textContent=time;$('#dateText').textContent=d.toLocaleDateString('es-UY',{weekday:'long',day:'numeric',month:'long'}).replace(/^./,x=>x.toUpperCase())}clock();setInterval(clock,1000);
let left=1500,running=false,timerId;function timerRender(){const m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');$('#timer').textContent=m+':'+s}$('#startTimer').onclick=()=>{running=!running;$('#startTimer').textContent=running?'Pausar':'Empezar';clearInterval(timerId);if(running)timerId=setInterval(()=>{if(left>0)left--;else{running=false;clearInterval(timerId)}timerRender()},1000)};$('#resetTimer').onclick=()=>{running=false;clearInterval(timerId);left=1500;$('#startTimer').textContent='Empezar';timerRender()};timerRender();
const notes=$('#notesBox');notes.value=localStorage.getItem('nexusNotes2')||'';notes.oninput=()=>localStorage.setItem('nexusNotes2',notes.value);
let playing=true;$('#playBtn').onclick=()=>{playing=!playing;$('#playBtn').innerHTML=playing?'<i data-lucide="pause"></i>':'<i data-lucide="play"></i>';lucide.createIcons()};render();