const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DAY=()=>new Date().toISOString().slice(0,10);
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const clean=s=>String(s).replace(/[<>]/g,'');
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};

const defaults=['Planificar el día','Trabajar en el proyecto','Entrenar','Leer algo','Tiempo libre','Ser la mejor versión de ti'];
let tasks=get('nexusTasks3',defaults.map((text,i)=>({id:Date.now()+i,text,done:i===0,priority:i===1?'alta':'normal',completedDate:i===0?DAY():null})));
let taskFilter='all';
function saveTasks(){set('nexusTasks3',tasks);renderTasks();renderStats()}
function taskHTML(t,full=false){return `<div class="task-row ${t.done?'done':''}"><input type="checkbox" data-task-check="${t.id}" ${t.done?'checked':''}><span class="task-text">${clean(t.text)}</span><span class="task-priority ${t.priority}">${t.priority}</span>${full?`<span class="task-actions"><button data-task-delete="${t.id}" title="Eliminar"><i data-lucide="trash-2"></i></button></span>`:''}</div>`}
function renderTasks(){
 const home=tasks.filter(t=>!t.done).slice(0,6);$('#taskList').innerHTML=(home.length?home:tasks.slice(0,6)).map(t=>taskHTML(t)).join('')||'<p>No hay tareas. Disfruta el espacio.</p>';
 const visible=tasks.filter(t=>taskFilter==='all'||(taskFilter==='done'?t.done:!t.done));$('#taskListFull').innerHTML=visible.map(t=>taskHTML(t,true)).join('')||'<p>No hay tareas en esta vista.</p>';
 const done=tasks.filter(t=>t.done).length,pct=tasks.length?Math.round(done/tasks.length*100):0;$('#taskHomeMeta').textContent=`${tasks.filter(t=>!t.done).length} pendientes`;$('#taskStatsLine').innerHTML=`<span style="width:${pct}%"></span>`;
 $$('[data-task-check]').forEach(x=>x.onchange=()=>{const t=tasks.find(t=>t.id==x.dataset.taskCheck);if(t){t.done=x.checked;t.completedDate=x.checked?DAY():null}saveTasks()});
 $$('[data-task-delete]').forEach(x=>x.onclick=()=>{tasks=tasks.filter(t=>t.id!=x.dataset.taskDelete);saveTasks();toast('Tarea eliminada')});
 const sel=$('#focusTask');const val=sel.value;sel.innerHTML='<option value="">Sin tarea específica</option>'+tasks.filter(t=>!t.done).map(t=>`<option value="${t.id}">${clean(t.text)}</option>`).join('');if([...sel.options].some(o=>o.value===val))sel.value=val;
 lucide.createIcons();
}
function openTaskForm(){navigate('home');$('#taskForm').classList.remove('hidden');$('#taskInput').focus()}
$('#addTaskBtn').onclick=()=>{$('#taskForm').classList.toggle('hidden');$('#taskInput').focus()};$('#taskAddFull').onclick=openTaskForm;
$('#taskForm').onsubmit=e=>{e.preventDefault();const v=$('#taskInput').value.trim();if(!v)return;tasks.unshift({id:Date.now(),text:v,done:false,priority:$('#taskPriority').value,completedDate:null});$('#taskInput').value='';$('#taskForm').classList.add('hidden');saveTasks();toast('Tarea creada')};
$$('[data-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});

function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo(0,0);if(id==='stats')renderStats();lucide.createIcons()}$$('.nav').forEach(n=>n.onclick=()=>navigate(n.dataset.view));

function clock(){const d=new Date(),time=d.toLocaleTimeString('es-UY',{hour:'2-digit',minute:'2-digit'}),date=d.toLocaleDateString('es-UY',{weekday:'long',day:'numeric',month:'long'}).replace(/^./,x=>x.toUpperCase());$('#clock').textContent=time;$('#bigClock').textContent=time;$('#dateText').textContent=date;$('#bigDate').textContent=date;const h=d.getHours();$('#greetingText').textContent=(h<12?'Buenos días':h<19?'Buenas tardes':'Buenas noches')+', Alan.'}clock();setInterval(clock,1000);

const weatherCodes={0:['☀️','Despejado'],1:['🌤️','Mayormente despejado'],2:['⛅','Parcialmente nublado'],3:['☁️','Nublado'],45:['🌫️','Niebla'],48:['🌫️','Niebla'],51:['🌦️','Llovizna'],53:['🌦️','Llovizna'],55:['🌧️','Llovizna intensa'],61:['🌧️','Lluvia'],63:['🌧️','Lluvia'],65:['🌧️','Lluvia intensa'],80:['🌦️','Chaparrones'],81:['🌧️','Chaparrones'],82:['⛈️','Chaparrones fuertes'],95:['⛈️','Tormenta']};
async function loadWeather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=-34.90&longitude=-54.95&current=temperature_2m,weather_code,wind_speed_10m&timezone=America%2FMontevideo');if(!r.ok)throw 0;const j=await r.json(),c=j.current,[ico,desc]=weatherCodes[c.weather_code]||['🌤️','Clima actual'];const temp=Math.round(c.temperature_2m)+'°C';$('#weatherIcon').textContent=ico;$('#weatherTemp').textContent=temp;$('#weatherDetailIcon').textContent=ico;$('#weatherDetailTemp').textContent=temp;$('#weatherDetailText').textContent=`${desc} · Viento ${Math.round(c.wind_speed_10m)} km/h · Maldonado`;set('nexusWeather',{temp,ico,desc,wind:c.wind_speed_10m})}catch{const w=get('nexusWeather',null);if(w){$('#weatherIcon').textContent=w.ico;$('#weatherTemp').textContent=w.temp;$('#weatherDetailIcon').textContent=w.ico;$('#weatherDetailTemp').textContent=w.temp;$('#weatherDetailText').textContent=w.desc+' · Maldonado'}else $('#weatherDetailText').textContent='No se pudo actualizar el clima.'}}
$('#weatherButton').onclick=()=>{loadWeather();toast('Actualizando clima')};loadWeather();

let focus=get('nexusFocus',{date:DAY(),sessions:0,minutes:0});if(focus.date!==DAY())focus={date:DAY(),sessions:0,minutes:0};
let total=1500,left=1500,running=false,timerId=null;
function timerRender(){const m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');$('#timer').textContent=m+':'+s;$('#focusSessionsToday').textContent=focus.sessions;$('#focusMinutesToday').textContent=focus.minutes}
function completeFocus(){running=false;clearInterval(timerId);focus.sessions++;focus.minutes+=Math.round(total/60);set('nexusFocus',focus);left=total;$('#startTimer').textContent='Empezar';timerRender();renderStats();toast('Sesión de enfoque completada ✦')}
$('#startTimer').onclick=()=>{running=!running;$('#startTimer').textContent=running?'Pausar':'Empezar';clearInterval(timerId);if(running)timerId=setInterval(()=>{left--;if(left<=0)completeFocus();timerRender()},1000)};
$('#resetTimer').onclick=()=>{running=false;clearInterval(timerId);left=total;$('#startTimer').textContent='Empezar';timerRender()};
$$('[data-minutes]').forEach(b=>b.onclick=()=>{running=false;clearInterval(timerId);total=Number(b.dataset.minutes)*60;left=total;$$('[data-minutes]').forEach(x=>x.classList.toggle('active',x===b));timerRender()});timerRender();

let habits=get('nexusHabits',[{id:1,name:'Planificar el día',history:{}},{id:2,name:'Mover el cuerpo',history:{}},{id:3,name:'Leer 20 minutos',history:{}}]);
function streak(h){let n=0,d=new Date();for(let i=0;i<365;i++){const k=d.toISOString().slice(0,10);if(h.history[k]){n++;d.setDate(d.getDate()-1)}else if(i===0){d.setDate(d.getDate()-1)}else break}return n}
function saveHabits(){set('nexusHabits',habits);renderHabits();renderStats()}
function renderHabits(){const done=habits.filter(h=>h.history[DAY()]).length,pct=habits.length?Math.round(done/habits.length*100):0;$('#habitPercent').textContent=pct+'%';$('#habitRing').style.background=`conic-gradient(#aeb5ff ${pct}%,rgba(255,255,255,.08) 0)`;$('#habitMiniProgress').textContent=pct+'% hoy';$('#habitMessage').textContent=pct===100?'Día completado.':pct>=50?'Vas por buen camino.':'Empieza por uno.';$('#habitSubtext').textContent=`${done} de ${habits.length} hábitos completados hoy.`;
 $('#habitList').innerHTML=habits.map(h=>`<div class="habit-row ${h.history[DAY()]?'done':''}"><button class="habit-check" data-habit="${h.id}"><i data-lucide="check"></i></button><div><strong>${clean(h.name)}</strong><div class="habit-meta">Racha: ${streak(h)} días</div></div><span class="habit-meta">${h.history[DAY()]?'Hecho':'Pendiente'}</span><button class="delete-btn" data-habit-delete="${h.id}"><i data-lucide="trash-2"></i></button></div>`).join('')||'<p>Crea tu primer hábito.</p>';
 $$('[data-habit]').forEach(b=>b.onclick=()=>{const h=habits.find(h=>h.id==b.dataset.habit);h.history[DAY()]=!h.history[DAY()];saveHabits()});$$('[data-habit-delete]').forEach(b=>b.onclick=()=>{habits=habits.filter(h=>h.id!=b.dataset.habitDelete);saveHabits()});lucide.createIcons()}
$('#newHabitBtn').onclick=()=>{$('#habitForm').classList.toggle('hidden');$('#habitInput').focus()};$('#habitForm').onsubmit=e=>{e.preventDefault();const v=$('#habitInput').value.trim();if(!v)return;habits.push({id:Date.now(),name:v,history:{}});$('#habitInput').value='';$('#habitForm').classList.add('hidden');saveHabits();toast('Hábito creado')};$('#betterMeBtn').onclick=$('#habitShortcut').onclick=()=>navigate('habits');renderHabits();

const sounds=[{name:'Brown Focus',type:'Ruido marrón profundo',kind:'brown'},{name:'Soft Rain',type:'Lluvia sintética',kind:'rain'},{name:'Night Air',type:'Ambiente suave',kind:'pink'}];
let soundIndex=get('nexusSoundIndex',0),volume=get('nexusVolume',45),audioCtx=null,source=null,gain=null,playing=false,progressTimer=null;
function noiseBuffer(kind){const rate=audioCtx.sampleRate,len=rate*3,b=audioCtx.createBuffer(1,len,rate),d=b.getChannelData(0);let last=0;for(let i=0;i<len;i++){const white=Math.random()*2-1;if(kind==='brown'){last=(last+.02*white)/1.02;d[i]=last*3.5}else if(kind==='pink'){d[i]=(white*.35)+(last*.65);last=d[i]}else d[i]=white*(Math.random()>.965?1:.28)}return b}
function stopSound(){if(source){try{source.stop()}catch{}source=null}playing=false;clearInterval(progressTimer);$('#audioState').textContent='Pausado';updatePlayIcons()}
function playSound(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();stopSound();gain=audioCtx.createGain();gain.gain.value=volume/100*.22;gain.connect(audioCtx.destination);source=audioCtx.createBufferSource();source.buffer=noiseBuffer(sounds[soundIndex].kind);source.loop=true;source.connect(gain);source.start();playing=true;$('#audioState').textContent='Reproduciendo';let p=0;progressTimer=setInterval(()=>{$('#audioProgress').style.width=((p++%100))+'%'},250);updatePlayIcons()}
function toggleSound(){playing?stopSound():playSound()}
function updatePlayIcons(){const icon=playing?'pause':'play';$('#playBtn').innerHTML=`<i data-lucide="${icon}"></i>`;$('#musicMasterPlay').innerHTML=`<i data-lucide="${icon}"></i> ${playing?'Pausar':'Reproducir'}`;lucide.createIcons()}
function renderSounds(){const s=sounds[soundIndex];$('#soundName').textContent=s.name;$('#soundType').textContent=s.type;$('#volumeText').textContent=volume+'%';$('#volumeSlider').value=volume;$('#soundGrid').innerHTML=sounds.map((x,i)=>`<button class="sound-option ${i===soundIndex?'active':''}" data-sound="${i}"><strong>${x.name}</strong><span>${x.type}</span></button>`).join('');$$('[data-sound]').forEach(b=>b.onclick=()=>{soundIndex=Number(b.dataset.sound);set('nexusSoundIndex',soundIndex);if(playing)playSound();renderSounds()})}
function changeSound(n){soundIndex=(soundIndex+n+sounds.length)%sounds.length;set('nexusSoundIndex',soundIndex);if(playing)playSound();renderSounds()}
$('#playBtn').onclick=$('#musicMasterPlay').onclick=toggleSound;$('#prevSound').onclick=()=>changeSound(-1);$('#nextSound').onclick=()=>changeSound(1);$('#soundDown').onclick=()=>setVolume(volume-10);$('#soundUp').onclick=()=>setVolume(volume+10);function setVolume(v){volume=Math.max(0,Math.min(100,v));set('nexusVolume',volume);if(gain)gain.gain.value=volume/100*.22;renderSounds()}$('#volumeSlider').oninput=e=>setVolume(Number(e.target.value));$('#favoriteSound').onclick=()=>$('#favoriteSound').classList.toggle('active');renderSounds();updatePlayIcons();

const notes=$('#notesBox');notes.value=localStorage.getItem('nexusNotes3')||'';let noteTimer;notes.oninput=()=>{clearTimeout(noteTimer);$('#notesSaved').textContent='Guardando...';noteTimer=setTimeout(()=>{localStorage.setItem('nexusNotes3',notes.value);$('#notesSaved').textContent='Guardado automáticamente'},350)};

const quotes=[['La motivación te inicia. La disciplina te mantiene.','NEXUS'],['No necesitas hacerlo todo. Necesitas hacer lo importante.','NEXUS'],['La constancia vuelve extraordinario lo que parecía pequeño.','NEXUS'],['Protege tu atención: ahí vive tu progreso.','NEXUS'],['Empieza antes de sentirte listo.','NEXUS'],['Un buen día también se construye con pequeños pasos.','NEXUS']];
let qi=get('nexusQuote',0);function renderQuote(){const [q,a]=quotes[qi];$('#homeQuote').innerHTML='“'+q+'”';$('#bigQuote').textContent='“'+q+'”';$('#quoteAuthor').textContent='— '+a;set('nexusQuote',qi)}function nextQuote(){qi=(qi+1)%quotes.length;renderQuote()}$('#quoteCard').onclick=nextQuote;$('#newQuoteBtn').onclick=nextQuote;renderQuote();

function renderStats(){const today=DAY(),doneToday=tasks.filter(t=>t.completedDate===today).length,habitsToday=habits.filter(h=>h.history[today]).length,maxStreak=habits.reduce((m,h)=>Math.max(m,streak(h)),0);$('#statTasks').textContent=doneToday;$('#statHabits').textContent=habitsToday;$('#statFocus').textContent=focus.minutes;$('#statStreak').textContent=maxStreak;
 const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10),score=tasks.filter(t=>t.completedDate===key).length+habits.filter(h=>h.history[key]).length;days.push({label:d.toLocaleDateString('es-UY',{weekday:'short'}).slice(0,2),score})}const max=Math.max(1,...days.map(d=>d.score));$('#weekChart').innerHTML=days.map(d=>`<div class="day-bar"><div class="bar-fill" style="height:${Math.max(5,d.score/max*145)}px"></div><span>${d.label}</span></div>`).join('')}
renderTasks();renderStats();